version: '3'
services:
  nginx:
    extends:
      file: ./nginx/docker-compose.yml
      service: nginx

  client:
    build: .

  api:
    build: api
    environment:
      MONGO_URI: mongodb://mongo:27017

  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"
    volumes:
    - mongo:/data
    environment: 
      AUTH: "no"

  stegapi:
    build: ./stegapi
    ports:
      - 5555:5000

volumes:
  mongo: {}
