version: "3"
services:
  nginx:
    logging:
      options:
        gelf-address: "udp://localhost:12201"
        tag: "nginx"
      driver: gelf
    image: nginx:1.23.2
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

      - /etc/letsencrypt/live/api.whataproof.xyz/fullchain.pem:/etc/letsencrypt/live/api.whataproof.xyz/fullchain.pem
      - /etc/letsencrypt/live/api.whataproof.xyz/privkey.pem:/etc/letsencrypt/live/api.whataproof.xyz/privkey.pem

      - /etc/letsencrypt/live/stegapi.whataproof.xyz/fullchain.pem:/etc/letsencrypt/live/stegapi.whataproof.xyz/fullchain.pem
      - /etc/letsencrypt/live/stegapi.whataproof.xyz/privkey.pem:/etc/letsencrypt/live/stegapi.whataproof.xyz/privkey.pem

      - /etc/letsencrypt/live/whataproof.xyz/fullchain.pem:/etc/letsencrypt/live/whataproof.xyz/fullchain.pem
      - /etc/letsencrypt/live/whataproof.xyz/privkey.pem:/etc/letsencrypt/live/whataproof.xyz/privkey.pem
