language: node_js
node_js:
  - lts/*
  - node
branches:
  only:
    - master
cache:
  npm: true
services:
  - mongodb
before_script:
  - npm install
os:
  - linux
script:
  - npm test
  - npm run coverage
